// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHSKIo_JWrb02jO_FbVpqiiLmtpX44rNE',
    appId: '1:1060872274388:android:52add56998977138f99641',
    messagingSenderId: '1060872274388',
    projectId: 'gemini-chatbot-37502',
    storageBucket: 'gemini-chatbot-37502.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYq6ffqyoacGCPJ0Q8gTBSs9f3-AUdjqU',
    appId: '1:1060872274388:ios:a8193d554b3658d3f99641',
    messagingSenderId: '1060872274388',
    projectId: 'gemini-chatbot-37502',
    databaseURL: 'https://gemini-chatbot-37502-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'gemini-chatbot-37502.firebasestorage.app',
    iosClientId: '1060872274388-ge18hb9hd9h3tmm4mfhohn2bg8up2vl2.apps.googleusercontent.com',
    iosBundleId: 'com.example.geminiChatBot',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBePNCj0S_QmBhpXe_vBCeMy4arTwP4zMc',
    appId: '1:1060872274388:web:cc4cd5c635231581f99641',
    messagingSenderId: '1060872274388',
    projectId: 'gemini-chatbot-37502',
    authDomain: 'gemini-chatbot-37502.firebaseapp.com',
    databaseURL: 'https://gemini-chatbot-37502-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'gemini-chatbot-37502.firebasestorage.app',
    measurementId: 'G-0M8XYB6C91',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYq6ffqyoacGCPJ0Q8gTBSs9f3-AUdjqU',
    appId: '1:1060872274388:ios:a8193d554b3658d3f99641',
    messagingSenderId: '1060872274388',
    projectId: 'gemini-chatbot-37502',
    databaseURL: 'https://gemini-chatbot-37502-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'gemini-chatbot-37502.firebasestorage.app',
    iosClientId: '1060872274388-ge18hb9hd9h3tmm4mfhohn2bg8up2vl2.apps.googleusercontent.com',
    iosBundleId: 'com.example.geminiChatBot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBePNCj0S_QmBhpXe_vBCeMy4arTwP4zMc',
    appId: '1:1060872274388:web:2be4c6a8028ede69f99641',
    messagingSenderId: '1060872274388',
    projectId: 'gemini-chatbot-37502',
    authDomain: 'gemini-chatbot-37502.firebaseapp.com',
    databaseURL: 'https://gemini-chatbot-37502-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'gemini-chatbot-37502.firebasestorage.app',
    measurementId: 'G-YKEJ49483Q',
  );

}